---
name: {{ NAME }}
env: {{ ENV }}

bind_addr: {{ HOST|default('0.0.0.0') }}
http_port: {{ PORT|default('8080') }}
redis_dsn: {{ REDIS_DSN|default('redis://127.16.25.1') }}
band_url: {{ BAND_URL|default('http://172.16.25.1:10000') }}

proxy_checker:
  list: {{ENDPOINT_PROXY_LIST}}
  regions: {{ENDPOINT_REGION_LIST}}
  auth: {{ENDPOINT_AUTH}}
  notify: {{PROXY_CHECK_NOTIFY}}


rucap_api_gw:
  rucaptcha_key: {{RUCAPTCHA_KEY}}

# Services  blocks
send_mixpanel:
  additiolan_channels: yes
  mixpanel_token: {{MIXPANEL_TOKEN}}
  mixpanel_api_secret: {{MIXPANEL_API_SECRET}}